### ISSUE TITLE
Developer consent and upstreaming

### ISSUE THREAD

**Issue by Madis0** [IMB11/Loqui#1]
As a mod developer and volunteer translator, I find this project in its current state concerning. 

Your premise is to "provide open-source translations for all mods", but by a quick glance I could already find at least 12 mods that already accept translations upstream, some of which even use Crowdin themselves.

So, why are you including mods that already accept translations on their mod upstream? Has there been any discussion with those devs?

Other mods that don't accept translations upstream yet - has there been discussions to notify them of this project, to then donate the translations done here for their upstream?

Edit: I read the readme about opting out, but I believe it should be _opt-in_, with you directly proposing the inclusion for each dev.

**Comment by Nucceteere** [comment]
If the mod already has translation files for a language on that version, that mod can't be translated to the already existing language inside the mod because of how Loqui was programed. However, if a specific version of that mod doesn't have the translations that the further versions do, that version can be translated to the languages that doesn't exist in that version because this mod aims on supporting every mod version. Unfortunately, Loqui cannot search for every mods translation pages because that would be very hard to implement + it would be resource consuming for a mod that doesn't get monetisation. About the opt-out, if the Devs of that mod have stopped caring about it, then those mods wouldn't have any translations, that essentially means that the people who doesn't know the language the mod was written in, then they would have a hard time playing.

**Comment by Madis0** [comment]
What if the mod will get that language upstream _after_ someone translated it on Loqui?
Or what if someone wants to upstream translations provided in Loqui? I don't see a defined workflow for that.

**Comment by Nucceteere** [comment]
1 - The further versions of that mod won't have translations on Loqui but older versions will still have them.

2 - They can download the translated lang files on the `output` branch of [mineblock11/loqui-translations](https://www.github.com/mineblock11/loqui-translations) and then slap it in their mod.

**Comment by IMB11** [comment]
The discussion of developer consent has been hugely debated in the Fabric and NeoForge discord, tldr:

- Loqui relies on an opt-out system in order to provide translations for as many mods as possible.
- Loqui also relies on people downloading the mod in order to expand the number of mods available - hence where there isn't many translations yet, as the mod has just released.
- The README.md file clearly states that an opt out system exists, and you can also globally opt out by adding your mod's language namespaces to src/api/src/blacklist.ts
- I've just realised that I haven't mentioned how versioning works in the description, I'll do that later today, but what @EngurRuzgar said is accurate.
- Upstreaming is mentioned in the description of the mod, see "For Mod Developers"

**Comment by IMB11** [comment]
As much as an opt-in system would be preferable, I can assure you that people wouldn't be arsed to opt-in.

**Comment by Madis0** [comment]
Thanks for the clarifications! It is good to know that you've thought about these cases.

I would still suggest you or one of your maintainers to contact the mods at some point, e.g. "our community fully translated your mod to 5 languages, would you like us to make a PR for it".

Another question I have is, what about Crowdin phrase limits? If the mod becomes popular and you hit the limit, what would you do?

**Comment by IMB11** [comment]
We've actually already hit the limit during development, since we're on the Crowdin Open Source plan, we essentially can request an increase with no problem. I've already increased the limit 4 times now (it's currently at 80,000 words (200,000 strings))

There is plans for lots of tools that integrate with Loqui, such as a web dashboard and potentially a gradle plugin that automatically downloads new translations on mod build, I will be releasing a roadmap shortly after the NeoForge version of Loqui is published.

**Comment by IMB11** [comment]
The roadmap also includes a webhook system that developers can register to, eg: create a github issue/discussion when a new translation is recieved or send a discord embed via a discord webhook.
